"""empty message

Revision ID: 35e0098d7400
Revises: 47e9d8129a98
Create Date: 2019-12-06 15:37:24.447400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e0098d7400'
down_revision = '47e9d8129a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gene_circuit', sa.Column('output_nodes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_gene_circuit_output_nodes'), 'gene_circuit', ['output_nodes'], unique=False)
    op.drop_index('ix_gene_circuit_output_node', table_name='gene_circuit')
    op.drop_column('gene_circuit', 'output_node')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gene_circuit', sa.Column('output_node', sa.INTEGER(), nullable=True))
    op.create_index('ix_gene_circuit_output_node', 'gene_circuit', ['output_node'], unique=False)
    op.drop_index(op.f('ix_gene_circuit_output_nodes'), table_name='gene_circuit')
    op.drop_column('gene_circuit', 'output_nodes')
    # ### end Alembic commands ###
