"""empty message

Revision ID: 3a2af16092cf
Revises: 6b421b165a40
Create Date: 2019-12-11 11:47:27.816033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2af16092cf'
down_revision = '6b421b165a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input__output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('gene_circuit', 'output_node')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gene_circuit', sa.Column('output_node', sa.INTEGER(), nullable=True))
    op.drop_table('input__output')
    # ### end Alembic commands ###
