"""empty message

Revision ID: 44e5e12210ab
Revises: 3a2af16092cf
Create Date: 2019-12-11 11:51:12.300628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e5e12210ab'
down_revision = '3a2af16092cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gene_circuit', 'output_node')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gene_circuit', sa.Column('output_node', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
