"""empty message

Revision ID: 47e9d8129a98
Revises: 
Create Date: 2019-12-06 14:56:04.362381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e9d8129a98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene_circuit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_name', sa.String(length=32), nullable=True),
    sa.Column('gene_nodes', sa.Integer(), nullable=True),
    sa.Column('output_node', sa.Integer(), nullable=True),
    sa.Column('input_nodes', sa.Integer(), nullable=True),
    sa.Column('topology', sa.String(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gene_circuit_circuit_name'), 'gene_circuit', ['circuit_name'], unique=True)
    op.create_index(op.f('ix_gene_circuit_gene_nodes'), 'gene_circuit', ['gene_nodes'], unique=False)
    op.create_index(op.f('ix_gene_circuit_input_nodes'), 'gene_circuit', ['input_nodes'], unique=False)
    op.create_index(op.f('ix_gene_circuit_output_node'), 'gene_circuit', ['output_node'], unique=False)
    op.create_index(op.f('ix_gene_circuit_topology'), 'gene_circuit', ['topology'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gene_circuit_topology'), table_name='gene_circuit')
    op.drop_index(op.f('ix_gene_circuit_output_node'), table_name='gene_circuit')
    op.drop_index(op.f('ix_gene_circuit_input_nodes'), table_name='gene_circuit')
    op.drop_index(op.f('ix_gene_circuit_gene_nodes'), table_name='gene_circuit')
    op.drop_index(op.f('ix_gene_circuit_circuit_name'), table_name='gene_circuit')
    op.drop_table('gene_circuit')
    # ### end Alembic commands ###
